# Generated by Django 2.2.1 on 2019-05-28 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0004_auto_20190523_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ltags',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
